import type { User, Menu, NewsCategory, News, Course, CourseSchedule, Gallery, Download, AppSettings } from "./types"

// Mock Users
export const mockUsers: User[] = [
  {
    id: "1",
    email: "admin@mejatika.com",
    password: "admin123", // In production, this would be hashed
    name: "Admin MEJATIKA",
    role: "admin",
    avatar: "/placeholder-user.jpg",
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
  },
  {
    id: "2",
    email: "contributor@mejatika.com",
    password: "contributor123",
    name: "Contributor User",
    role: "contributor",
    avatar: "/placeholder-user.jpg",
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
  },
  {
    id: "3",
    email: "peserta@mejatika.com",
    password: "peserta123",
    name: "Peserta Kursus",
    role: "participant",
    avatar: "/placeholder-user.jpg",
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
  },
]

// Mock Menus
export const mockMenus: Menu[] = [
  {
    id: "1",
    title: "Beranda",
    url: "/",
    order: 1,
    parentId: null,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "2",
    title: "Tentang",
    url: "/tentang",
    order: 2,
    parentId: null,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "3",
    title: "Profil",
    url: "/tentang/profil",
    order: 1,
    parentId: "2",
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "4",
    title: "Visi & Misi",
    url: "/tentang/visi-misi",
    order: 2,
    parentId: "2",
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "5",
    title: "Berita",
    url: "/berita",
    order: 3,
    parentId: null,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "6",
    title: "Kursus",
    url: "/kursus",
    order: 4,
    parentId: null,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "7",
    title: "Galeri",
    url: "/galeri",
    order: 5,
    parentId: null,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "8",
    title: "Download",
    url: "/download",
    order: 6,
    parentId: null,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "9",
    title: "Kontak",
    url: "/kontak",
    order: 7,
    parentId: null,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
]

// Mock News Categories
export const mockNewsCategories: NewsCategory[] = [
  { id: "1", name: "Pengumuman", slug: "pengumuman", createdAt: new Date(), updatedAt: new Date() },
  { id: "2", name: "Acara", slug: "acara", createdAt: new Date(), updatedAt: new Date() },
  { id: "3", name: "Prestasi", slug: "prestasi", createdAt: new Date(), updatedAt: new Date() },
  { id: "4", name: "Beasiswa", slug: "beasiswa", createdAt: new Date(), updatedAt: new Date() },
  { id: "5", name: "Umum", slug: "umum", createdAt: new Date(), updatedAt: new Date() },
]

// Mock News
export const mockNews: News[] = [
  {
    id: "1",
    title: "Pembukaan Pendaftaran Kursus Periode Januari 2025",
    slug: "pembukaan-pendaftaran-kursus-januari-2025",
    excerpt:
      "MEJATIKA membuka pendaftaran kursus untuk periode Januari 2025 dengan berbagai program pelatihan menarik.",
    content:
      "MEJATIKA dengan bangga mengumumkan pembukaan pendaftaran kursus untuk periode Januari 2025. Kami menyediakan berbagai program pelatihan yang dirancang khusus untuk meningkatkan keterampilan dan kompetensi peserta.",
    image: "/placeholder.jpg?height=400&width=600&query=online+learning",
    categoryId: "1",
    authorId: "1",
    status: "published",
    publishedAt: new Date("2024-12-15"),
    createdAt: new Date("2024-12-15"),
    updatedAt: new Date("2024-12-15"),
  },
  {
    id: "2",
    title: "Workshop Digital Marketing: Strategi Pemasaran Era Modern",
    slug: "workshop-digital-marketing-2025",
    excerpt:
      "Ikuti workshop digital marketing dan pelajari strategi pemasaran terkini untuk mengembangkan bisnis Anda.",
    content:
      "Workshop Digital Marketing akan membahas strategi pemasaran digital yang efektif, termasuk SEO, social media marketing, dan content marketing.",
    image: "/placeholder.jpg?height=400&width=600&query=digital+marketing+workshop",
    categoryId: "2",
    authorId: "2",
    status: "published",
    publishedAt: new Date("2024-12-14"),
    createdAt: new Date("2024-12-14"),
    updatedAt: new Date("2024-12-14"),
  },
  {
    id: "3",
    title: "Siswa MEJATIKA Raih Juara Lomba Desain Grafis Nasional",
    slug: "juara-lomba-desain-grafis-nasional",
    excerpt:
      "Prestasi membanggakan! Siswa MEJATIKA berhasil meraih juara 1 dalam lomba desain grafis tingkat nasional.",
    content:
      "Kami dengan bangga mengumumkan bahwa siswa MEJATIKA berhasil meraih juara 1 dalam lomba desain grafis tingkat nasional yang diselenggarakan di Jakarta.",
    image: "/placeholder.jpg?height=400&width=600&query=graphic+design+award",
    categoryId: "3",
    authorId: "1",
    status: "published",
    publishedAt: new Date("2024-12-13"),
    createdAt: new Date("2024-12-13"),
    updatedAt: new Date("2024-12-13"),
  },
  {
    id: "4",
    title: "Beasiswa Penuh untuk 10 Peserta Berprestasi",
    slug: "beasiswa-penuh-peserta-berprestasi",
    excerpt:
      "MEJATIKA memberikan beasiswa penuh untuk 10 peserta berprestasi. Daftar sekarang dan raih kesempatan emas ini!",
    content:
      "Program beasiswa MEJATIKA hadir untuk mendukung talenta terbaik Indonesia. Kami menyediakan beasiswa penuh untuk 10 peserta dengan kriteria tertentu.",
    image: "/placeholder.jpg?height=400&width=600&query=scholarship+education",
    categoryId: "4",
    authorId: "1",
    status: "published",
    publishedAt: new Date("2024-12-12"),
    createdAt: new Date("2024-12-12"),
    updatedAt: new Date("2024-12-12"),
  },
  {
    id: "5",
    title: "Sertifikasi Internasional untuk Lulusan Program Unggulan",
    slug: "sertifikasi-internasional-program-unggulan",
    excerpt:
      "Dapatkan sertifikasi internasional yang diakui industri global setelah menyelesaikan program unggulan MEJATIKA.",
    content:
      "Program unggulan MEJATIKA kini dilengkapi dengan sertifikasi internasional yang diakui oleh industri global, meningkatkan daya saing lulusan.",
    image: "/placeholder.jpg?height=400&width=600&query=international+certification",
    categoryId: "1",
    authorId: "2",
    status: "published",
    publishedAt: new Date("2024-12-11"),
    createdAt: new Date("2024-12-11"),
    updatedAt: new Date("2024-12-11"),
  },
  {
    id: "6",
    title: "Kolaborasi MEJATIKA dengan Perusahaan Teknologi Terkemuka",
    slug: "kolaborasi-perusahaan-teknologi",
    excerpt:
      "MEJATIKA menjalin kerjasama strategis dengan perusahaan teknologi terkemuka untuk program magang dan perekrutan.",
    content:
      "Kerjasama ini membuka peluang bagi peserta MEJATIKA untuk mendapatkan pengalaman kerja langsung dan kesempatan karir di industri teknologi.",
    image: "/placeholder.jpg?height=400&width=600&query=technology+partnership",
    categoryId: "5",
    authorId: "1",
    status: "published",
    publishedAt: new Date("2024-12-10"),
    createdAt: new Date("2024-12-10"),
    updatedAt: new Date("2024-12-10"),
  },
]

// Mock Courses
export const mockCourses: Course[] = [
  {
    id: "1",
    title: "Web Development Fundamental",
    description: "Pelajari dasar-dasar pengembangan web dari HTML, CSS, hingga JavaScript",
    image: "/placeholder.jpg?height=300&width=400&query=web+development",
    duration: "3 Bulan",
    instructor: "Budi Santoso",
    price: 2500000,
    status: "active",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "2",
    title: "Mobile App Development",
    description: "Kuasai pengembangan aplikasi mobile Android dan iOS menggunakan React Native",
    image: "/placeholder.jpg?height=300&width=400&query=mobile+app+development",
    duration: "4 Bulan",
    instructor: "Siti Aminah",
    price: 3500000,
    status: "active",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "3",
    title: "Digital Marketing",
    description: "Strategi pemasaran digital lengkap untuk meningkatkan penjualan online",
    image: "/placeholder.jpg?height=300&width=400&query=digital+marketing+course",
    duration: "2 Bulan",
    instructor: "Ahmad Rizki",
    price: 1500000,
    status: "active",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
]

// Mock Course Schedules
export const mockCourseSchedules: CourseSchedule[] = [
  {
    id: "1",
    courseId: "1",
    title: "Web Development - Batch 12",
    startDate: new Date("2025-01-15"),
    endDate: new Date("2025-04-15"),
    time: "19:00 - 21:00 WIB",
    location: "Online via Zoom",
    maxParticipants: 30,
    currentParticipants: 18,
    status: "upcoming",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "2",
    courseId: "2",
    title: "Mobile App - Batch 8",
    startDate: new Date("2025-01-20"),
    endDate: new Date("2025-05-20"),
    time: "19:00 - 21:30 WIB",
    location: "Online via Zoom",
    maxParticipants: 25,
    currentParticipants: 12,
    status: "upcoming",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "3",
    courseId: "3",
    title: "Digital Marketing - Batch 15",
    startDate: new Date("2025-01-10"),
    endDate: new Date("2025-03-10"),
    time: "19:00 - 21:00 WIB",
    location: "Hybrid (Online & Offline)",
    maxParticipants: 40,
    currentParticipants: 35,
    status: "upcoming",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "4",
    courseId: "1",
    title: "Web Development - Batch 11",
    startDate: new Date("2024-10-15"),
    endDate: new Date("2025-01-15"),
    time: "19:00 - 21:00 WIB",
    location: "Online via Zoom",
    maxParticipants: 30,
    currentParticipants: 28,
    status: "ongoing",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
]

// Mock Gallery
export const mockGallery: Gallery[] = [
  {
    id: "1",
    title: "Workshop Web Development 2024",
    description: "Dokumentasi kegiatan workshop web development",
    image: "/placeholder.jpg?height=300&width=400&query=workshop+classroom",
    category: "Workshop",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "2",
    title: "Wisuda Angkatan 12",
    description: "Acara wisuda peserta kursus angkatan 12",
    image: "/placeholder.jpg?height=300&width=400&query=graduation+ceremony",
    category: "Acara",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "3",
    title: "Pelatihan Mobile Development",
    description: "Suasana pelatihan mobile app development",
    image: "/placeholder.jpg?height=300&width=400&query=mobile+training",
    category: "Pelatihan",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
]

// Mock Downloads
export const mockDownloads: Download[] = [
  {
    id: "1",
    title: "Formulir Pendaftaran Kursus",
    description: "Download formulir pendaftaran kursus MEJATIKA",
    fileUrl: "/files/formulir-pendaftaran.pdf",
    fileSize: "250 KB",
    fileType: "PDF",
    downloadCount: 145,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "2",
    title: "Brosur Program Kursus 2025",
    description: "Informasi lengkap program kursus tahun 2025",
    fileUrl: "/files/brosur-2025.pdf",
    fileSize: "1.2 MB",
    fileType: "PDF",
    downloadCount: 89,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "3",
    title: "Panduan Peserta Kursus",
    description: "Panduan lengkap untuk peserta kursus",
    fileUrl: "/files/panduan-peserta.pdf",
    fileSize: "500 KB",
    fileType: "PDF",
    downloadCount: 234,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
]

// Mock App Settings
export const mockAppSettings: AppSettings[] = [
  {
    id: "1",
    key: "site_name",
    value: "MEJATIKA",
    type: "text",
    description: "Nama website",
    updatedAt: new Date(),
  },
  {
    id: "2",
    key: "site_description",
    value: "Platform Pembelajaran dan Pelatihan Digital Terpadu",
    type: "text",
    description: "Deskripsi website",
    updatedAt: new Date(),
  },
  {
    id: "3",
    key: "contact_email",
    value: "info@mejatika.com",
    type: "text",
    description: "Email kontak",
    updatedAt: new Date(),
  },
  {
    id: "4",
    key: "contact_phone",
    value: "+62 21 1234 5678",
    type: "text",
    description: "Nomor telepon",
    updatedAt: new Date(),
  },
  {
    id: "5",
    key: "running_text",
    value:
      "Pendaftaran dibuka untuk periode Januari 2025 | Dapatkan diskon 20% untuk pendaftar awal | Hubungi kami untuk informasi lebih lanjut",
    type: "text",
    description: "Teks berjalan di homepage",
    updatedAt: new Date(),
  },
  {
    id: "6",
    key: "enable_registration",
    value: "true",
    type: "boolean",
    description: "Aktifkan pendaftaran",
    updatedAt: new Date(),
  },
]
